import React, { useState } from 'react'
import { api } from '../api'

const SECTIONS = [
  { key: 'summary', label: 'Executive summary' },
  { key: 'documentation', label: 'Documentation log' },
  { key: 'descriptives', label: 'Descriptive stats' },
  { key: 'tests', label: 'Hypothesis tests' },
  { key: 'models', label: 'Model performance' },
]

export default function ReportPage({ dataset }) {
  const [selected, setSelected] = useState(SECTIONS.map((s) => s.key))
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)

  if (!dataset) return <p style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>Upload a dataset first.</p>

  const toggle = (key) => {
    setSelected(selected.includes(key) ? selected.filter((k) => k !== key) : [...selected, key])
  }

  const build = async () => {
    setLoading(true)
    try {
      const r = await api.buildReport(dataset.id, selected)
      setReport(r)
    } finally {
      setLoading(false)
    }
  }

  const exportJson = () => {
    if (!report) return
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `simucast_report_${dataset.name}.json`
    a.click()
  }

  const reportHtml = () => {
    if (!report) return ''
    return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(report.title)} report</title>
  <style>
    body { font-family: Arial, sans-serif; color: #1f2933; margin: 36px; line-height: 1.45; }
    h1 { margin: 0 0 4px; font-size: 24px; }
    h2 { margin: 24px 0 8px; font-size: 17px; border-bottom: 1px solid #d9dee7; padding-bottom: 4px; }
    .meta { color: #667085; font-size: 12px; margin-bottom: 22px; }
    .entry { padding: 8px 10px; border: 1px solid #e5e7eb; border-radius: 6px; margin: 6px 0; font-size: 12px; }
    .entry strong { text-transform: capitalize; }
    table { border-collapse: collapse; width: 100%; font-size: 12px; margin-top: 8px; }
    th, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; }
    th { background: #f5f7fa; }
    @media print { body { margin: 20mm; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(report.title)}</h1>
  <div class="meta">Generated by SimuCast - ${new Date(report.generated_at).toLocaleString()}</div>
  ${report.sections.map(sectionHtml).join('')}
</body>
</html>`
  }

  const exportHtml = () => {
    if (!report) return
    const blob = new Blob([reportHtml()], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `simucast_report_${dataset.name}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  const printReport = () => {
    if (!report) return
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(reportHtml())
    w.document.close()
    w.focus()
    w.print()
  }

  return (
    <>
      <h1 className="ax-page-title">Auto-report</h1>
      <p className="ax-page-sub">AI-written narrative combining your analyses · toggle sections to include.</p>

      <div style={{ display: 'grid', gridTemplateColumns: '200px 1fr', gap: 14 }}>
        <div>
          <p className="ax-lbl">Sections</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {SECTIONS.map((s) => (
              <label key={s.key} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, cursor: 'pointer' }}>
                <input type="checkbox" checked={selected.includes(s.key)} onChange={() => toggle(s.key)} />
                {s.label}
              </label>
            ))}
          </div>
          <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 6 }}>
            <button className="ax-btn prim" disabled={loading} onClick={build}>
              {loading ? 'Generating…' : 'Generate report'}
            </button>
            <button className="ax-btn" disabled={!report} onClick={printReport}>Print report</button>
            <button className="ax-btn" disabled={!report} onClick={exportHtml}>Export HTML</button>
            <button className="ax-btn" disabled={!report} onClick={exportJson}>Export JSON</button>
          </div>
        </div>

        <div className="ax-card" style={{ padding: 18, minHeight: 400 }} id="ax-report-preview">
          {!report ? (
            <p style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>
              Press "Generate report" to build a document from your current analyses.
            </p>
          ) : (
            <>
              <p style={{ fontSize: 18, fontWeight: 500, margin: 0 }}>{report.title}</p>
              <p style={{ fontSize: 11, color: 'var(--color-text-secondary)', margin: '2px 0 16px' }}>
                Generated by SimuCast · {new Date(report.generated_at).toLocaleString()}
              </p>

              {report.sections.map((sec, i) => (
                <div key={i} style={{ marginBottom: 18 }}>
                  <p style={{ fontSize: 14, fontWeight: 500, margin: '0 0 6px' }}>{sec.title}</p>
                  {sec.body && (
                    <p style={{ fontSize: 12, color: 'var(--color-text-secondary)', margin: 0, lineHeight: 1.6 }}>{sec.body}</p>
                  )}
                  {sec.data?.stats && (
                    <table className="ax-tbl" style={{ fontSize: 11, marginTop: 6 }}>
                      <thead>
                        <tr><th>Variable</th><th>n</th><th>Mean</th><th>SD</th><th>Min</th><th>Max</th></tr>
                      </thead>
                      <tbody>
                        {sec.data.stats.filter((s) => s.kind === 'numeric').map((s) => (
                          <tr key={s.variable}>
                            <td>{s.variable}</td>
                            <td>{s.n?.toLocaleString()}</td>
                            <td>{s.mean?.toFixed(3) ?? '—'}</td>
                            <td>{s.std?.toFixed(3) ?? '—'}</td>
                            <td>{s.min?.toFixed(3) ?? '—'}</td>
                            <td>{s.max?.toFixed(3) ?? '—'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                  {sec.items && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 6 }}>
                      {sec.items.map((it, j) => (
                        <div key={j} style={{ fontSize: 11, color: 'var(--color-text-secondary)', padding: '4px 8px', background: 'var(--color-background-secondary)', borderRadius: 4 }}>
                          {it.created_at && <span>{new Date(it.created_at).toLocaleString()} - </span>}
                          {it.kind && <strong>{it.kind}: </strong>}
                          {it.name && <strong>{it.name} ({it.algorithm}): </strong>}
                          {it.summary || it.result?.interpretation || formatInline(it.metrics) || JSON.stringify(it.result || it.metrics).slice(0, 120)}
                          {(it.detail?.notes || []).map((n) => (
                            <p key={n.id} style={{ margin: '4px 0 0', color: 'var(--color-text-primary)' }}>
                              Note: {n.text}
                            </p>
                          ))}
                          {it.detail?.mapping && (
                            <p style={{ margin: '4px 0 0' }}>
                              Mapping: {Object.entries(it.detail.mapping).map(([from, to]) => `${from} to ${to}`).join('; ')}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </>
          )}
        </div>
      </div>
    </>
  )
}

function formatInline(m) {
  if (!m) return ''
  if (m.task === 'classification') {
    const parts = [`accuracy ${(m.accuracy * 100).toFixed(1)}%`]
    if (m.auc != null) parts.push(`AUC ${m.auc.toFixed(3)}`)
    return parts.join(', ')
  }
  if (m.task === 'regression') {
    return `R² ${m.r2?.toFixed(3) ?? '—'}, RMSE ${m.rmse?.toFixed(3) ?? '—'}`
  }
  return ''
}

function sectionHtml(sec) {
  const body = sec.body ? `<p>${escapeHtml(sec.body)}</p>` : ''
  const stats = sec.data?.stats
    ? `<table><thead><tr><th>Variable</th><th>n</th><th>Mean</th><th>SD</th><th>Min</th><th>Max</th></tr></thead><tbody>${
        sec.data.stats.filter((s) => s.kind === 'numeric').map((s) => (
          `<tr><td>${escapeHtml(s.variable)}</td><td>${s.n ?? ''}</td><td>${fmtHtml(s.mean)}</td><td>${fmtHtml(s.std)}</td><td>${fmtHtml(s.min)}</td><td>${fmtHtml(s.max)}</td></tr>`
        )).join('')
      }</tbody></table>`
    : ''
  const items = sec.items
    ? sec.items.map((it) => (
        `<div class="entry">${
          it.created_at ? `${escapeHtml(new Date(it.created_at).toLocaleString())} - ` : ''
        }${it.kind ? `<strong>${escapeHtml(it.kind)}</strong>: ` : ''}${
          escapeHtml(it.summary || it.result?.interpretation || formatInline(it.metrics) || JSON.stringify(it.result || it.metrics || it.detail || {}).slice(0, 180))
        }${notesHtml(it.detail?.notes)}${mappingHtml(it.detail?.mapping)}</div>`
      )).join('')
    : ''
  return `<section><h2>${escapeHtml(sec.title)}</h2>${body}${stats}${items}</section>`
}

function notesHtml(notes) {
  if (!notes?.length) return ''
  return `<div style="margin-top:6px;"><strong>Notes:</strong>${notes.map((n) => `<div>${escapeHtml(n.text)}</div>`).join('')}</div>`
}

function mappingHtml(mapping) {
  if (!mapping) return ''
  return `<details style="margin-top:6px;"><summary>Category mapping</summary><ul>${
    Object.entries(mapping).map(([from, to]) => `<li>${escapeHtml(from)} to ${escapeHtml(to)}</li>`).join('')
  }</ul></details>`
}

function fmtHtml(v) {
  return typeof v === 'number' ? v.toFixed(3) : ''
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
