import React, { useState } from 'react'
import { api } from '../api'

const SECTIONS = [
  { key: 'summary', label: 'Executive summary' },
  { key: 'documentation', label: 'Documentation log' },
  { key: 'descriptives', label: 'Descriptive stats' },
  { key: 'tests', label: 'Hypothesis tests' },
  { key: 'models', label: 'Model performance' },
]

export default function ReportPage({ dataset }) {
  const [selected, setSelected] = useState(SECTIONS.map((s) => s.key))
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)

  if (!dataset) return <p style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>Upload a dataset first.</p>

  const toggle = (key) => {
    setSelected(selected.includes(key) ? selected.filter((k) => k !== key) : [...selected, key])
  }

  const build = async () => {
    setLoading(true)
    try {
      const r = await api.buildReport(dataset.id, selected)
      setReport(r)
    } finally {
      setLoading(false)
    }
  }

  const exportJson = () => {
    if (!report) return
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `simucast_report_${dataset.name}.json`
    a.click()
  }

  const printReport = () => window.print()

  return (
    <>
      <h1 className="ax-page-title">Auto-report</h1>
      <p className="ax-page-sub">AI-written narrative combining your analyses · toggle sections to include.</p>

      <div style={{ display: 'grid', gridTemplateColumns: '200px 1fr', gap: 14 }}>
        <div>
          <p className="ax-lbl">Sections</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {SECTIONS.map((s) => (
              <label key={s.key} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, cursor: 'pointer' }}>
                <input type="checkbox" checked={selected.includes(s.key)} onChange={() => toggle(s.key)} />
                {s.label}
              </label>
            ))}
          </div>
          <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 6 }}>
            <button className="ax-btn prim" disabled={loading} onClick={build}>
              {loading ? 'Generating…' : 'Generate report'}
            </button>
            <button className="ax-btn" disabled={!report} onClick={printReport}>Print / PDF</button>
            <button className="ax-btn" disabled={!report} onClick={exportJson}>Export JSON</button>
          </div>
        </div>

        <div className="ax-card" style={{ padding: 18, minHeight: 400 }} id="ax-report-preview">
          {!report ? (
            <p style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>
              Press "Generate report" to build a document from your current analyses.
            </p>
          ) : (
            <>
              <p style={{ fontSize: 18, fontWeight: 500, margin: 0 }}>{report.title}</p>
              <p style={{ fontSize: 11, color: 'var(--color-text-secondary)', margin: '2px 0 16px' }}>
                Generated by SimuCast · {new Date(report.generated_at).toLocaleString()}
              </p>

              {report.sections.map((sec, i) => (
                <div key={i} style={{ marginBottom: 18 }}>
                  <p style={{ fontSize: 14, fontWeight: 500, margin: '0 0 6px' }}>{sec.title}</p>
                  {sec.body && (
                    <p style={{ fontSize: 12, color: 'var(--color-text-secondary)', margin: 0, lineHeight: 1.6 }}>{sec.body}</p>
                  )}
                  {sec.data?.stats && (
                    <table className="ax-tbl" style={{ fontSize: 11, marginTop: 6 }}>
                      <thead>
                        <tr><th>Variable</th><th>n</th><th>Mean</th><th>SD</th><th>Min</th><th>Max</th></tr>
                      </thead>
                      <tbody>
                        {sec.data.stats.filter((s) => s.kind === 'numeric').map((s) => (
                          <tr key={s.variable}>
                            <td>{s.variable}</td>
                            <td>{s.n?.toLocaleString()}</td>
                            <td>{s.mean?.toFixed(3) ?? '—'}</td>
                            <td>{s.std?.toFixed(3) ?? '—'}</td>
                            <td>{s.min?.toFixed(3) ?? '—'}</td>
                            <td>{s.max?.toFixed(3) ?? '—'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                  {sec.items && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 6 }}>
                      {sec.items.map((it, j) => (
                        <div key={j} style={{ fontSize: 11, color: 'var(--color-text-secondary)', padding: '4px 8px', background: 'var(--color-background-secondary)', borderRadius: 4 }}>
                          {it.created_at && <span>{new Date(it.created_at).toLocaleString()} - </span>}
                          {it.kind && <strong>{it.kind}: </strong>}
                          {it.name && <strong>{it.name} ({it.algorithm}): </strong>}
                          {it.summary || it.result?.interpretation || formatInline(it.metrics) || JSON.stringify(it.result || it.metrics).slice(0, 120)}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </>
          )}
        </div>
      </div>
    </>
  )
}

function formatInline(m) {
  if (!m) return ''
  if (m.task === 'classification') {
    const parts = [`accuracy ${(m.accuracy * 100).toFixed(1)}%`]
    if (m.auc != null) parts.push(`AUC ${m.auc.toFixed(3)}`)
    return parts.join(', ')
  }
  if (m.task === 'regression') {
    return `R² ${m.r2?.toFixed(3) ?? '—'}, RMSE ${m.rmse?.toFixed(3) ?? '—'}`
  }
  return ''
}
